### PR TITLE
Issues 34:  Cut the csv to smaller files.

### PR DESCRIPTION
**Pull request by wesleycheung0**
https://github.com/Greenstand/treetracker-airflow-dags/issues/34

### CODE REVIEW

**Comment by dadiorchen** [comment]
@huang-pan could you take a loot at this?

**Comment by huang-pan** [comment]
> @huang-pan could you take a loot at this?

ok

**Comment by wesleycheung0** [comment]
@huang-pan let me know if any question. Feel free to DM me on slack. 

@dadiorchen what would be the ideal size per chunk? Currently the chunk size is set to 1MB, which is unrealistically small.

**Comment by dadiorchen** [comment]
@wesleycheung0 The size is fine and we can adjust this at any time, I will merge this first, and I'm working on restore the ckan service online, some then we can try to test this out

**Comment by dadiorchen** [comment]
@wesleycheung0 thank you for your work!

**Comment by huang-pan** [comment]
Sorry guys, I've been pretty busy this past week, didn't have a chance to look at it.

**Comment by dadiorchen** [comment]
@huang-pan fully understand!

**Pull request merged**
